/*

When enabling Multicurrency, historical transactions may need database help to bring them along

*/

DECLARE @Statement VARCHAR(8000)
DECLARE @TABLENAME VARCHAR(500)

DECLARE CURR CURSOR
FOR
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'CURRNIDX'
	AND COLUMN_DEFAULT IS NOT NULL

OPEN CURR

FETCH NEXT
FROM CURR
INTO @TABLENAME

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @Statement = 'SELECT * INTO ' + @TABLENAME + '_BAK FROM ' + @TABLENAME

	EXEC (@Statement)

	SET @Statement = 'UPDATE ' + @TABLENAME + ' SET CURRNIDX = [NEW CURRENCY ID] WHERE CURRNIDX = [OLD CURRENCY ID]'

	EXEC (@Statement)

	FETCH NEXT
	FROM CURR
	INTO @TABLENAME
END

CLOSE CURR

DEALLOCATE CURR
